// frameworks/keyed/solid/src/main.jsx
import { createSignal, createSelector, batch } from 'solid-js';
import { render } from 'solid-js/dom';

let idCounter = 1;
const adjectives = ["pretty", "large", "big", "small", "tall", "short", "long", "handsome", "plain", "quaint", "clean", "elegant", "easy", "angry", "crazy", "helpful", "mushy", "odd", "unsightly", "adorable", "important", "inexpensive", "cheap", "expensive", "fancy"],
  colours = ["red", "yellow", "blue", "green", "pink", "brown", "purple", "brown", "white", "black", "orange"],
  nouns = ["table", "chair", "house", "bbq", "desk", "car", "pony", "cookie", "sandwich", "burger", "pizza", "mouse", "keyboard"];

function _random (max) { return Math.round(Math.random() * 1000) % max; };

function buildData(count) {
  let data = new Array(count);
  for (let i = 0; i < count; i++) {
    data[i] = {
      id: idCounter++,
      label: `${adjectives[_random(adjectives.length)]} ${colours[_random(colours.length)]} ${nouns[_random(nouns.length)]}`
    }
  }
  return data;
}

const Button = ({ id, text, fn }) =>
  <div class='col-sm-6 smallpad'>
    <button id={ id } class='btn btn-primary btn-block' type='button' onClick={ fn }>{ text }</button>
  </div>

const App = () => {
  const [data, setData] = createSignal([]),
    [selected, setSelected] = createSignal(null, true),
    isSelected = createSelector(selected);

  return <div class='container'>
    <div class='jumbotron'><div class='row'>
      <div class='col-md-6'><h1>SolidJS Keyed</h1></div>
      <div class='col-md-6'><div class='row'>
        <Button id='run' text='Create 1,000 rows' fn={ run } />
        <Button id='runlots' text='Create 10,000 rows' fn={ runLots } />
        <Button id='add' text='Append 1,000 rows' fn={ add } />
        <Button id='update' text='Update every 10th row' fn={ update } />
        <Button id='clear' text='Clear' fn={ clear } />
        <Button id='swaprows' text='Swap Rows' fn={ swapRows } />
      </div></div>
    </div></div>
    <table class='table table-hover table-striped test-data'><tbody>
      <For each={ data() }>{ row => {
        let rowId = row.id;
        return <tr class={isSelected(rowId) ? "danger": ""}>
          <td class='col-md-1' textContent={ rowId } />
          <td class='col-md-4'><a onClick={[setSelected, rowId]} textContent={ row.label } /></td>
          <td class='col-md-1'><a onClick={[remove, rowId]}><span class='glyphicon glyphicon-remove' aria-hidden="true" /></a></td>
          <td class='col-md-6'/>
        </tr>
      }}</For>
    </tbody></table>
    <span class='preloadicon glyphicon glyphicon-remove' aria-hidden="true" />
  </div>;

  function remove(id) {
    const d = data();
    d.splice(d.findIndex(d => d.id === id), 1);
    setData(d);
  }

  function run() {
    batch(() => {
      setData(buildData(1000));
      setSelected(null);
    });
  }

  function runLots() {
    batch(() => {
      setData(buildData(10000));
      setSelected(null);
    });
  }

  function add() { setData(data().concat(buildData(1000))); }

  function update() {
    const d = data().slice();
    let index = 0;
    while (index < d.length) {
      d[index] = {...d[index], label: d[index].label + ' !!!'};
      index += 10;
    }
    setData(d);
  }

  function swapRows() {
    const d = data();
    if (d.length > 998) {
      let tmp = d[1];
      d[1] = d[998];
      d[998] = tmp;
      setData(d);
    }
  }

  function clear() {
    batch(() => {
      setData([]);
      setSelected(null);
    });
  }
}

render(App, document.getElementById("main"));

// frameworks/keyed/react-use-spy/src/main.jsx
import React, { memo }  from "react";
import { render } from "react-dom";
import { spy, useSpy } from "./use-spy";

const A = ["pretty", "large", "big", "small", "tall", "short", "long", "handsome", "plain", "quaint", "clean",
  "elegant", "easy", "angry", "crazy", "helpful", "mushy", "odd", "unsightly", "adorable", "important", "inexpensive",
  "cheap", "expensive", "fancy"];
const C = ["red", "yellow", "blue", "green", "pink", "brown", "purple", "brown", "white", "black", "orange"];
const N = ["table", "chair", "house", "bbq", "desk", "car", "pony", "cookie", "sandwich", "burger", "pizza", "mouse",
  "keyboard"];

const random = (max) => Math.round(Math.random() * 1000) % max;

let nextId = 1;

const buildData = (count) => {
  const res = [];
  let index = 0;

  for (; index < count; ++index) {
    res.push({
      id: nextId++,
      label: `${A[random(A.length)]} ${C[random(C.length)]} ${N[random(N.length)]}`
    })
  }

  return res;
}

const dataState = spy([]);
const selectedState = spy(0);

const update = (data) => {
  const newData = data.slice();
  let index = 0;
  let length = newData.length;
  let temp;

  for (; index < length; index += 10) {
    temp = newData[index];

    newData[index] = { id: temp.id, label: temp.label + " !!!" };
  }

  return newData;
};

const remove = (item) => (data) => {
  const newData = data.slice();

  newData.splice(data.indexOf(item), 1);

  return newData;
};

const swapRows = (data) => {
  const newData = data.slice();
  const tmp = newData[1];

  newData[1] = newData[998];
  newData[998] = tmp;

  return newData;
};

const Row = memo(({ item, isSelected }) => (
    <tr className={isSelected ? "danger" : ""}>
      <td className="col-md-1">{item.id}</td>
      <td className="col-md-4">
        <a onClick={() => selectedState.$ = (item.id)}>{item.label}</a>
      </td>
      <td className="col-md-1">
        <a onClick={() => dataState.$ = (remove(item))}><span className="glyphicon glyphicon-remove" aria-hidden="true"/></a>
      </td>
      <td className="col-md-6"/>
    </tr>
));

const RowList = () => {
  const data = useSpy(dataState);
  const selected = useSpy(selectedState);

  return data.map((item) => <Row key={item.id} item={item} isSelected={item.id === selected} />);
};

const Button = ({ id, title, cb }) => (
  <div className="col-sm-6 smallpad">
    <button type="button" className="btn btn-primary btn-block" id={id} onClick={cb}>{title}</button>
  </div>
);

const Main = () => (
  <div className="container">
    <div className="jumbotron">
      <div className="row">
        <div className="col-md-6"><h1>React Use Spy</h1></div>
        <div className="col-md-6"><div className="row">
          <Button id="run" title="Create 1,000 rows" cb={() => dataState.$ = buildData(1000)} />
          <Button id="runlots" title="Create 10,000 rows" cb={() => dataState.$ = buildData(10000)} />
          <Button id="add" title="Append 1,000 rows" cb={() => dataState.$ = dataState.$.concat(buildData(1000))} />
          <Button id="update" title="Update every 10th row" cb={() => dataState.$ = update(dataState.$)} />
          <Button id="clear" title="Clear" cb={() => dataState.$ = ([])} />
          <Button id="swaprows" title="Swap Rows" cb={() => dataState.$ = swapRows(dataState.$)} />
        </div></div>
      </div>
    </div>
    <table className="table table-hover table-striped test-data">
      <tbody>
        <RowList />
      </tbody>
    </table>
    <span className="preloadicon glyphicon glyphicon-remove" aria-hidden="true"/>
  </div>
);

render(
  <Main />,
  document.getElementById("main")
);
